# Generated by Django 4.1.7 on 2023-03-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateTimeField()),
                ('DOJ', models.DateTimeField()),
                ('Department', models.TextField(blank=True, max_length=50, null=True)),
                ('Post', models.TextField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, max_length=100, null=True)),
                ('City', models.TextField(blank=True, max_length=50, null=True)),
                ('Country', models.TextField(blank=True, max_length=50, null=True)),
                ('Zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.TextField(blank=True, max_length=50, null=True)),
                ('Active', models.BooleanField(blank=True, default=False, null=True)),
                ('Leave_count', models.CharField(blank=True, max_length=50, null=True)),
                ('On_leave', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
