# Generated by Django 4.1.7 on 2023-03-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sope', '0002_alter_employee_dob_alter_employee_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Leave_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Zipcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
