# Generated by Django 4.1.7 on 2023-03-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sope', '0004_alter_employee_dob_alter_employee_doj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='DOJ',
            field=models.DateField(blank=True, null=True),
        ),
    ]
